name: Run Test.sh

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: latest

      - name: Install dependencies
        run: |
          apt update
          sudo apt install valgrind &
          pip install norminette &
          wait
      
      - name: Run Test
        run: |
          chmode +x test.sh
          ./test.sh
